# Generated by Django 3.2.9 on 2021-12-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_attendance', '0002_auto_20211215_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='group',
            new_name='department',
        ),
    ]
