# Generated by Django 3.2.9 on 2022-01-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_attendance', '0003_alter_attendancesheet_break_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
