# Generated by Django 3.2.9 on 2021-12-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_attendance', '0004_remove_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesheet',
            name='break_hours',
            field=models.IntegerField(),
        ),
    ]
