# Generated by Django 3.2.9 on 2021-12-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceEntry',
            new_name='AttendanceSheet',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
