# Generated by Django 3.2.9 on 2021-12-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_attendance', '0003_rename_group_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
